### PR TITLE
Readme edits

### PR DESCRIPTION
**Pull request by Bradamant3**

### CODE REVIEW

**Comment by hausdorff** [comment]
@Bradamant3 Since this is so old, I'm going to go ahead and close this review. Feel free to open it if you still need something from me here.

**Comment by Bradamant3** [comment]
So changes are not merged -- I'm not used to merging my own PRs, and I might originally have thought that I didn't have write permissions to the repo (which I evidently do). Do we still want the version that I submitted the PR for?

**Comment by hausdorff** [comment]
I think the version you wrote is good, but:

* It's now out of date.
* Adding `package.json` to the `.gitignore` is probably not what we want to do, since it's a pretty important file.
* Changing the default Jsonnet executable path to point at `"~/src/kube.libsonnet/bin"` is also probably not the right thing to do for users.

**Comment by hausdorff** [comment]
In other words, if we fix those 3 things, I don't see any particular reasons why this shouldn't proceed forward.

**Pull request closed without merging**
